name: Flask CI

on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: unbuntu-latest

steps:
  -name: checkout code
   uses: actions/checkout@v2
   
  -name: set up python
   uses: actions/setup-python@v2
   with: 
     python-version: 3.8
     
  -name: Create virtual enviroment
   run: |
     python -m nevn venv
     source venv/bin/activate

  -name: Install dependencies
   run: |
     python -m pip install --upgrade pip
     python -m pip install -r requirements.txt

  -name: Print debugging information
   run: |
     echo "python Version: $(python -version)"
     echo "Working Directory: $(pwd)"
     echo "Contents of Working Directory:$(ls -l)"
     echo "Contents of site_packages: $(ls -l venv/lib/python*/site_packages)"

  -name: Run test
   run: python test_hello.py
